=== saomari/ProjetWeb/WebContent/WEB-INF/XML-DATABASE/candidats.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="candidatType">
        <xs:all>
            <xs:element name="prenom" type="xs:string" />
            <xs:element name="nom" type="xs:string" />
            <xs:element name="email" type="xs:string" />
            <xs:element name="mdp" type="xs:string" />
            <xs:element name="sexe" type="xs:string" />
            <xs:element name="naissance" type="xs:string" />
            <xs:element name="nationalite" type="xs:string" />
            <xs:element name="adresse" type="xs:string" />
        </xs:all>
    </xs:complexType>
    <xs:element name="candidats">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="candidat" maxOccurs="unbounded" type="candidatType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== saomari/ProjetWeb/WebContent/WEB-INF/XML-DATABASE/candidats.xml
<?xml version="1.0" encoding="UTF-8" ?>
<candidats xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="candidats.xsd">
    <candidat>
        <prenom>Emmanuel</prenom>
        <nom>Doulin</nom>
        <email>e.doulin@mail.com</email>
        <mdp>password</mdp>
        <sexe>Féminin</sexe>
        <naissance>1988-12-03</naissance>
        <nationalite>Français</nationalite>
        <adresse>7 Rue du Temple</adresse>
        <tel>0780750880</tel>
    </candidat>
</candidats>
